### ISSUE TITLE
Android N

### ISSUE THREAD

**Issue by MAndretti** [jaredrummler/AndroidProcesses#23] opened 2016-06-04 09:02 UTC
Hi,

thanks for this gerat lib. I am porting my app to Android N and i know, the lib is not working with Android N.

But, what is the error? Can you Fix the error? Can i help you?

Thanks,
Mario

**Comment by jaredrummler** [comment] 2016-06-04 10:43
The problem is that listing the directory `/proc` returns permission denied errors. Try the following in ADB shell:

```
> adb shell
$ run-as com.your.packagename
$ ls /proc
```

example output:

```
ls: /proc/1: Permission denied
ls: /proc/2: Permission denied
ls: /proc/3: Permission denied
...
```

On all previous versions of Android, `/proc` was readable. What confuses me is that permissions on the directory haven't changed. This could be some SELinux problem.

I haven't had time to look into this in more detail so any suggestions or a workaround would be appreciated.

**Comment by tjmille2** [comment] 2016-06-30 15:44
Bump. I really enjoy this library, and appreciate all your work thus far. Any work to bring it up to Android N compatibility would be much appreciated.

**Comment by hpetander** [comment] 2016-07-18 06:21
Bump. Thanks for writing the library, it's been very useful. Having it working on Android N would be great!

**Comment by FabianTerhorst** [comment] 2016-07-19 12:54
@jaredrummler you opened a issue at http://b.android.com/ ?

**Comment by jaredrummler** [comment] 2016-07-26 12:38
http://stackoverflow.com/questions/38590140/file-system-changes-in-android-nougat

**Comment by jaredrummler** [comment] 2016-07-29 13:48
You will need to use UsageStatsManager or have root access to get a list of running processes on Android Nougat. See https://code.google.com/p/android/issues/detail?id=205565

**Comment by deviant-studio** [comment] 2016-09-10 15:04
there is no access to the /proc even with root privileges :(

**Comment by jaredrummler** [comment] 2016-09-10 16:36
@deviant-studio, it should work. What have you tried so far? Maybe I'll update the library to use root if available on Android 7.0+.

**Comment by deviant-studio** [comment] 2016-09-10 19:12
@jaredrummler i'm trying:
```
su
top -n 1 -s cpu -m 10
```

**Comment by jaredrummler** [comment] 2016-09-16 23:20
@deviant-studio it works:

```
angler:/ $ getprop ro.build.version.sdk
24
angler:/ $ su -v
2.78:SUPERSU
angler:/ $ su
angler:/ # top -n 1 -s cpu -m 10
User 2%, System 11%, IOW 0%, IRQ 0%
User 3 + Nice 0 + Sys 12 + Idle 87 + IOW 0 + IRQ 1 + SIRQ 0 = 103

  PID USER     PR  NI CPU% S  #THR     VSS     RSS PCY Name
 7398 root     20   0   6% R     1   9104K   1884K  fg top
  239 root     RT   0   0% S     1      0K      0K  fg cfinteractive
 5980 u0_a35   20   0   0% S    26 2311060K  87952K  fg com.google.android.googlequicksearchbox:search
    4 root     20   0   0% S     1      0K      0K  fg kworker/0:0
    5 root      0 -20   0% S     1      0K      0K  fg kworker/0:0H
    6 root     20   0   0% D     1      0K      0K  fg kworker/u16:0
    7 root     RT   0   0% S     1      0K      0K  fg migration/0
    8 root     20   0   0% S     1      0K      0K  fg rcu_preempt
    9 root     20   0   0% S     1      0K      0K  fg rcu_bh
   10 root     20   0   0% S     1      0K      0K  fg rcu_sched
```

`top` and `ps` should work as the shell user too because it has readproc (3009).

**Comment by diegorribeiro** [comment] 2016-09-27 22:21
I am using in my app to AndroidProcess +
compile 'eu.chainfire: libsuperuser: 1.0.0 +.'

is there any way this passage return all running processes
Android N?

public static List <Process> getRunningApps () {
        List <Process> processes = new ArrayList <> ();
        List <String> stdout = Shell.SH.run ( "toolbox ps -p -P -x -c");
        myPid android.os.Process.myPid int = ();
        for (String line: stdout) {
            try {
                Process process = new Process (line);
                if (process.user.matches (APP_ID_PATTERN)) {
                    if (process.ppid == || myPid process.name.equals ( "toolbox")) {
                        // Skip the processes we created to get the running apps.
                        continues;
                    }
                    processes.add (process);
                }
            } Catch (Exception e) {
                android.util.Log.d (TAG, "Failed parsing line" + line);
            }
        }
        return processes;
    }

**Comment by jaredrummler** [comment] 2016-10-14 19:33
@kswlee I downloaded the app. It does not get all running apps (it just showed one for me). If you decompile the app, you can see it is using `top`. You can decompile the APK using [jadx](https://github.com/skylot/jadx) or [enjarify](https://github.com/google/enjarify).

**Comment by kswlee** [comment] 2016-10-15 17:53
@jaredrummler I tried nexus 5x (with latest Android 7.0), and it shows more than one process ... weird 

![image](https://cloud.githubusercontent.com/assets/674724/19412204/5c8ef560-9343-11e6-9143-37cb2603e759.png)

**Comment by deviant-studio** [comment] 2016-11-29 15:54
Hey guys, take a look into https://play.google.com/store/apps/details?id=mobi.infolife.taskmanager
It doesn't require root. Though it still can show (and kill) processes on Android 7.1

**Comment by jaredrummler** [comment] 2016-12-25 10:06
I am closing this and may deprecate this library soon. I suggest using `UsageStatsManager` or, if availalbe, running `ps` in a root shell. It's nice to know `getRunningServices` will return some information regarding running processes. At first Google planned on having a permission to allow apps to read from /proc but they decided against this. Hopefully they will allow developers and users access to /proc in the future.

**Closed by jaredrummler** 2016-12-25 10:06 UTC

**Comment by huxq17** [comment] 2017-02-05 06:26
Unfortunately, /proc is unaccessible on N.

**Comment by pankajtalaviya97** [comment] 2017-04-26 05:42
My mobile os is N (Naugat)

so not getting all running processes through this method
so help me how to get all running application process in Android Naugat?

public static List getRunningApps () {
        List processes = new ArrayList <> ();
        List stdout = Shell.SH.run ( "toolbox ps -p -P -x -c");
        myPid android.os.Process.myPid int = ();
        for (String line: stdout) {
            try {
                Process process = new Process (line);
                if (process.user.matches (APP_ID_PATTERN)) {
                    if (process.ppid == || myPid process.name.equals ( "toolbox")) {
                        // Skip the processes we created to get the running apps.
                        continues;
                    }
                    processes.add (process);
                }
            } Catch (Exception e) {
                android.util.Log.d (TAG, "Failed parsing line" + line);
            }
        }
        return processes;
    }
