### ISSUE TITLE
The method ‘getRunningAppProcesses’ only works on 5.0+

### ISSUE THREAD

**Issue by MegatronKing** [jaredrummler/AndroidProcesses#13] opened 2016-01-29 06:42 UTC
Thank you for your library. But I test the function on Android 4.2, the field 'group' of class ControlGroup's value is "/", so the list of RunningAppProcesses is empty.

**Comment by jaredrummler** [comment] 2016-01-29 08:45
I have confirmed this does not work on Android 4.2. If I run `adb shell toolbox ps -P` it does give me the policy ("fg" or "bg"). I looked at the source for the jb-mr1-release and it looks like both `ps` and `top` get the scheduling policy from `/proc/<pid>/cgroup` (see [here](https://github.com/android/platform_system_core/blob/jb-mr1-release/toolbox/ps.c#L166-172) and [here](https://github.com/android/platform_system_core/blob/jb-mr1-release/libcutils/sched_policy.c#L161-220)). However, in my emulator /proc/<pid>/cgroup does not exist. Strange.

I'll look more into this in the coming week. For now, I would use `ProcessManager.getRunningAppProcessInfo(ctx)` to get a list of running apps. This will use `ActivityManager` on anything below Android 5.1.1. PR welcome :smile:

**Comment by MegatronKing** [comment] 2016-01-29 10:08
Thank you very much for your answer. 
However, I run adb shell toolbox ps -P and get the policy ("fg" or "bg") accurately, and in my real mobile not emulator proc/<pid>/cgroup exists too.

**Comment by jaredrummler** [comment] 2016-01-29 10:17
Will you please run the command `cat /proc/<pid>/cgroup` and paste the output here? Replace pid with your app PID (or any other app's PID).

**Comment by MegatronKing** [comment] 2016-02-02 05:50
on android 4.2 :
shell@android:/ $ cat /proc/11154/cgroup
cat /proc/11154/cgroup
2:cpu:/apps
1:cpuacct:/uid/10028

on android 5.1:
shell@aries:/ $ cat /proc/18632/cgroup
cat /proc/18632/cgroup
4:cpu:/apps
2:memory:/
1:cpuacct:/uid_10076/pid_18632

Obviously, there is only uid no pid on Android 4.2.

**Comment by jaredrummler** [comment] 2016-02-02 05:58
@MegatronKing Thanks for posting that. You should try `1.0.5`, it should be working now.

**Comment by MegatronKing** [comment] 2016-02-02 06:35
=_=
I have run the latest code, and the policy of Stat seems to be always 0. 
All processes are foreground.

**Comment by jaredrummler** [comment] 2016-02-02 06:37
Can you check if `/dev/cpuctl/tasks` exists on your device? This would be much easier to fix if I had a device running Android 4.2 :disappointed:

Thanks!

**Comment by MegatronKing** [comment] 2016-02-02 06:46
shell@android:/ $ ls /dev/cpuctl/
ls /dev/cpuctl/
apps
cgroup.clone_children
cgroup.event_control
cgroup.procs
cpu.rt_period_us
cpu.rt_runtime_us
cpu.shares
notify_on_release
release_agent
tasks

**Comment by fbesoain** [comment] 2016-02-02 16:30
Hi, 

I confirm the issue on Android 4.2, the API get all the processes in Backgound and Foreground as foregorund.
I check the directory cpuctl and the device has the task file, but I cannot access it  (Permission denied). 

`shell@vivaltods5m:/dev/cpuctl $ ls -l                                          
drwxr-xr-x root     root              2016-02-02 17:08 apps
-rw-r--r-- root     root            0 2016-02-02 17:08 cgroup.clone_children
--w--w--w- root     root            0 2016-02-02 17:08 cgroup.event_control
-rw-r--r-- root     root            0 2016-02-02 17:08 cgroup.procs
-r--r--r-- root     root            0 2016-02-02 17:08 cgroup.sane_behavior
-rw-r--r-- root     root            0 2016-02-02 17:08 cpu.rt_period_us
-rw-r--r-- root     root            0 2016-02-02 17:08 cpu.rt_runtime_us
-rw-r--r-- root     root            0 2016-02-02 17:08 cpu.shares
-rw-r--r-- root     root            0 2016-02-02 17:08 notify_on_release
-rw-r--r-- root     root            0 2016-02-02 17:08 release_agent
-rw-rw---- system   system          0 2016-02-02 17:08 tasks`

**Comment by fbesoain** [comment] 2016-02-02 18:58
I was studying the codea little bit and I found this so far:
On the class AndroidAppProcess on the line 68. `foreground = stat.policy() == 0; ` it's always true.
On a device with Android 4.2 with Kernel 3.10 all the running process on stat.policy() are 0 on the item 40 of the stat file.

**Comment by fbesoain** [comment] 2016-02-03 09:42
After checking for a while I've made it work. I've attached the Patch. 
[local_history2.patch.zip](https://github.com/jaredrummler/AndroidProcesses/files/115400/local_history2.patch.zip)

**Comment by jaredrummler** [comment] 2016-02-05 18:28
@MegatronKing will you please try the latest commit and see if that resolves the problem. I don't have a device running Android 4.2 or lower and the emulator does not support scheduled groups so I need someone to test this on an actual device. I won't push to maven until I'm sure this bug is resolved.

Thank you for your help so far.

**Comment by MarcoAltran** [comment] 2016-02-08 01:06
I've tested the `ProcessManager.getRunningForegroundApps(context)` on 4.1.2 but it shows a list of all running process. On 6.0.1 Nexus 5 works fine. For SDK versions lower than 21, I have implemented the old `getRunningTasks()`

**Comment by jaredrummler** [comment] 2016-02-08 07:48
@MarcoAltran Thanks for testing that out. Did you test with the latest commit or latest released version on maven?

**Comment by MarcoAltran** [comment] 2016-02-08 17:40
I've tried the latest version on maven. Now I have tried with last commit and it shows much less process, but there still a lot of noise. For example, com.android.contact always shows as a foreground process. Using the old method, everything works fine. In my Nexus 5 6.0.1 sometimes it shows more than one process, but by getting the last one I was able to have accurate results.

I can share my code of my workaround if you want.

**Comment by jaredrummler** [comment] 2016-02-09 20:05
@MarcoAltran Thanks for testing that. Some system apps with have the foreground policy even if they aren't displaying. You can check the oom_score_adj or oom_value to see which app is most likely the actual foreground app, however, on later versions of Android those files may need be readable for system apps.

I have released 1.0.6. As far as I can tell, the bug has been fixed. Again, I don't have a device running Android 4.2 so I cannot fully test this since the emulator doesn't support scheduled groups. I will close this issue but please leave a comment if you find any further errors on Android 4.2-. Thanks.

**Closed by jaredrummler** 2016-02-09 20:05 UTC
Labels: bug, help wanted

**Comment by xiaobinji** [comment] 2016-03-01 10:03
Thank you for your library.but i test the function on android 4.4.2(device:HUAWEI MT7-CL00).the result is empty;
shell@hwmt7:/ $ cat /proc/27807/cgroup
2:cpu:/apps/bg_non_interactive
1:freezer:/

i test on android 5.1(device:魅蓝 note 2) ,it is ok.
it is strange.haha
so i use getRunningAppProcessInfo instead.
